fix iio_aducm3029 project build
a recent change in aducm3029 platform drivers created a linker
error when building this project.

undefined reference to `no_os_irq_unregister_callback'
... (undefined references to all used no_os_irq_* functions)

Signed-off-by: Darius Berghe <darius.berghe@analog.com>